<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Python on Lionel Blog</title><link>https://hybirdego.github.io/tags/python/</link><description>Recent content in Python on Lionel Blog</description><generator>Hugo</generator><language>ko-kr</language><lastBuildDate>Fri, 16 May 2025 23:11:23 +0900</lastBuildDate><atom:link href="https://hybirdego.github.io/tags/python/index.xml" rel="self" type="application/rss+xml"/><item><title>Python uv</title><link>https://hybirdego.github.io/post/2025-05-22-python_uv/</link><pubDate>Fri, 16 May 2025 23:11:23 +0900</pubDate><guid>https://hybirdego.github.io/post/2025-05-22-python_uv/</guid><description>&lt;h1 id="python-uv-사용법">Python UV 사용법&lt;/h1>
&lt;ul>
&lt;li>
&lt;p>회사에서 uv python install 잘 안될 때
사용 중인 네트워크(예: 회사 네트워크)가 Zscaler, Cisco Umbrella 같은 프록시를 통해 SSL 검사를 수행하고 있을 가능성이 높습니다. 이 경우, 프록시가 중간에 자체 인증서를 삽입하여 uv가 사용하는 기본 인증서 저장소(Mozilla의 webpki-roots)에서 이를 신뢰하지 못해 UnknownIssuer 에러가 발생합니다.&lt;/p></description></item></channel></rss>